# Site settings
title: Opensource and security in mind
email: huynhok.uit@vnoss.org
description: > # this means to ignore newlines until "baseurl:"
  Severus's interesting things
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://infosec.xyz" # the base hostname & protocol for your site
twitter_username: Ngo_Huy
github_username:  NgoHuy
linkedin_username: 
# Build settings
markdown: kramdown
plugins: 
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
