# Site settings
title: Opensource and security in mind
email: huynhok.uit@vnoss.org
description: > # this means to ignore newlines until "baseurl:"
  Opensource and security in mind
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.severus.xyz" # the base hostname & protocol for your site
twitter_username: Ngo_Huy
github_username:  NgoHuy

# Build settings
markdown: kramdown
